spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/young?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: "mobikok@2020"
    initialSize: 1
    minIdle: 1
    maxIdle: 5
    maxActive: 50
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 10000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters: stat
    redis:
      host: 127.0.0.1
      port: 6379
      password: mobikok@2020
      timeout: 1000s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
      database: 0
      #     连接池配置，2.0中直接使用jedis或者lettuce配置连接池
      lettuce:
        pool:
          # 最大空闲连接数
          max-idle: 500
          # 最小空闲连接数
          min-idle: 50
          # 等待可用连接的最大时间，负数为不限制
          max-wait: -1
          # 最大活跃连接数，负数为不限制
          max-active: -1
    cache:
      redis:
        time-to-live: -1 #毫秒
    # 上传文件总的最大值
    # 单个文件的最大值
    servlet:
      multipart:
        max-file-size: 1000MB
        max-request-size: 500MB
        enabled: true
    application:
      name: seata-commodity

  mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
  #feign的配置，连接超时及读取超时配置
  feign:
    client:
      config:
        default:
          connectTimeout: 5000 #连接超时
          readTimeout: 5000 #读取超时
          loggerLevel: basic #日志等级
    okhttp:
      enabled: true
    hystrix:
      enabled: true
  #logging
  logging:
    level:
      com.young.seata.order.mapper: debug
      com.xt.open.jmall.product.remote.feignclients.CartFeignClient: debug
seata:
  enabled: true
  tx-service-group: my_test_tx_group
  application-id: seata-commodity
  config:
    type: nacos
    nacos:
      namespace: ""
      server-addr: nacos.blogyg.cn:9999
      group: "DEFAULT_GROUP"
      username: "nacos"
      password: "nacos"
      cluster: DEFAULT
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: nacos.blogyg.cn:9999
      group : "DEFAULT_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
      cluster: DEFAULT
